version: "3.9"

services:
  api:
    build: api
    image: ${API_DOCKER_NAME}
    container_name: ${API_DOCKER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGID=1000
      - PUID=1000
      - VIRTUAL_HOST=${API_DOCKER_DOMAIN}
    volumes:
      - ../../:/server
      - ./api:/docker-scripts
    networks:
      docker-net:
        aliases:
          - ${API_DOCKER_NAME}-app
    # depends_on:
    #     - db
    entrypoint: /docker-scripts/init_container.sh
  # db:
  #     image: jsurf/rpi-mariadb
  #     build: db
  #     container_name: ${API_DOCKER_NAME}-db
  #     restart: unless-stopped
  #     ports:
  #         - ${DB_DOCKER_PORT}:3306
  #     volumes:
  #         - ./db/data:/var/lib/mysql
  #         - ./db/scripts:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: ${DB_DOCKER_PASS}
  #         MYSQL_USER: ${DB_DOCKER_USER}
  #         MYSQL_PASSWORD: ${DB_DOCKER_PASS}
  #         MYSQL_DATABASE: ${DB_DOCKER_DATABASE}
  #     networks:
  #         docker-net:
  #             aliases:
  #                 - '${API_DOCKER_NAME}-db'

networks:
  docker-net:
    driver: bridge
    external: ${NET_EXTERNAL}
