openapi: 3.0.0
info:
  title: API NodeJs Template
  description: Plantilla de API en Node para desarrollos
  version: 1.0.0
  x-logo:
    url: /docs/assets/logo.svg
    backgroundColor: '#FFFFFF'
    altText: Logo
  contact:
    name: Jesús.T
    url: https://portfolio.Smartfulcode.com
    email: jesus@jetiradoro.com
servers:
  - url: https://api.smartfulcode.com
    description: Sandbox environment server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Tests
paths:
  /example:
    get:
      tags:
        - Tests
      summary: Example
      description: Endpoint de ejemplo para validar que la API responde correctamente
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '71'
            ETag:
              schema:
                type: string
                example: W/"47-ivQPCTVWqjOBQz1xCMS/9+wBHbQ"
            Date:
              schema:
                type: string
                example: Fri, 16 Aug 2024 10:53:29 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                status: success
                message: ''
                data:
                  api: api.smartfulcode.com
        '401':
          description: Unauthorized
          headers:
            Date:
              schema:
                type: string
                example: Fri, 16 Aug 2024 10:49:37 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '104'
            Connection:
              schema:
                type: string
                example: keep-alive
            access-control-allow-origin:
              schema:
                type: string
                example: '*'
            Cache-Control:
              schema:
                type: string
                example: public, max-age=0, must-revalidate
            etag:
              schema:
                type: string
                example: W/"68-bIZFIkwv7zDibJy4UonpZ9r+VIY"
            strict-transport-security:
              schema:
                type: string
                example: max-age=63072000
            x-powered-by:
              schema:
                type: string
                example: Express
            x-vercel-cache:
              schema:
                type: string
                example: BYPASS
            x-vercel-id:
              schema:
                type: string
                example: cdg1::cdg1::z9vpd-1723805376369-4c2a295464b6
            CF-Cache-Status:
              schema:
                type: string
                example: DYNAMIC
            Report-To:
              schema:
                type: string
                example: >-
                  {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=WHD1hd6qtkhItyCoM%2FKiv6pycxu7BfwSBQZoL8gsnfup1LFk3MeIZHxcZCMfZuipjKPnscPjeGUtlvfIbjWR4YMoyjMKsas4Y8OyQjVuP5X0Z8C%2FhZfee8Jxtci%2BPRfpFAZ4UHPEXQ%3D%3D"}],"group":"cf-nel","max_age":604800}
            NEL:
              schema:
                type: string
                example: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
            Server:
              schema:
                type: string
                example: cloudflare
            CF-RAY:
              schema:
                type: string
                example: 8b40dbd1eca0cc70-MAD
            alt-svc:
              schema:
                type: string
                example: h3=":443"; ma=86400
          content:
            application/json:
              schema:
                type: object
              example:
                status: error
                message: Unauthorized token request
                errors:
                  - El token es incorrecto! (secreto)
